# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multMat <- function(m1, m2) {
    .Call('_GPEDM_multMat', PACKAGE = 'GPEDM', m1, m2)
}

matrix2vector <- function(m) {
    .Call('_GPEDM_matrix2vector', PACKAGE = 'GPEDM', m)
}

innerProd <- function(x, y) {
    .Call('_GPEDM_innerProd', PACKAGE = 'GPEDM', x, y)
}

